# _config.yml

# site settings
title: Xiaoh's Blog
SEOTitle: Xiaoh写文字的地方 | Xiaoh's Blog
header-img: img/home-bg.jpg
email: xiaoh@about.me
description: "死生切阔，与子成说，执子之手，与子偕老。| 这里是 Xiaoh 的个人博客 | 外接各种互联网项目"
keyword: "兴明, xiaoh, pmars, itpmars, topmars, xiaoh's Blog, 博客, 个人网站, 互联网, 开发, 产品"
url: "http://www.xiaoh.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# sns settings
RSS: false
weibo_username:     topmars
zhihu_username:     xiaoh
github_username:    pmars

# build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# analytics settings
# Baidu Analytics
ba_track_id: eb09bda7042f7733bd1bcba14d69d750
# Google Analytics
ga_track_id: 'UA-73800419-1'            # Format: UA-xxxxxx-xx
ga_domain: www.xiaoh.me

# sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，玩玩游戏，交交朋友。世界那么大，带媳妇去看看。^V^"
sidebar-avatar: /img/avatar-xiaoh.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "pmars的博客",
        href: "http://pmars.cnblogs.com"
    },{
        title: "pmars的微博",
        href: "http://weibo.com/topmars"
    },{
        title: "我的项目",
        href: "http://github.com/pmars"
    }
]
